config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { registrations: "registrations"}
  resources :contacts do
    resource :report
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/thankyou', to: 'pages#thankyou'
  get '/error', to: 'pages#error'
  get '/faq', to: 'pages#faq'
   get '/landing2', to: 'pages#landing2'
  resources :contacts
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: { message: "Please enter a valid name" }, length: { maximum: 50 }, allow_blank: false 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i	
  validates :email, presence: { message: "Please enter a valid email" }, length: { maximum: 255 }, allow_blank: false,
                    format: {message: "Please enter  a valid email" , with: VALID_EMAIL_REGEX }
  validates :url, presence: { message: "Please enter  a valid url" }, length: { maximum: 50 }, allow_blank: false
  has_one :admin
  has_one :report
end  

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    contacts_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:url]
      
      #ContactMailer.contact_email(name, email, body).deliver
      
      flash[:success] = "Message sent."
      redirect_to thankyou_path
    else
      flash[:danger] = "Message not sent."
      redirect_to error_path
    end  
  end 
  def index
    if admin_signed_in?
     @contacts = Contact.all
    else
      redirect_to root_path
    end 
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :url) 
    end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @contact = Contact.new
  end
  
  def thankyou
    @contact = Contact.new
  end  
  
  def error
    @contact = Contact.new
  end
  
  def landing2
    @contact = Contact.new
  end  
  
end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController
  
   
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_admin_registered?, only: [:new, :create]
  
  protected

  def one_admin_registered?
    if ((Admin.count == 1) & (admin_signed_in?))
      redirect_to contacts_path
    elsif Admin.count == 1
      redirect_to new_admin_session_path
    end  
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  #before_action :authenticate_Contact!
  #before_action :only_current_Contact
  
  def new
    # form where a Contact can fill out their own report.
    @contact = Contact.find( params[:contact_id] )
    @report = Report.new
  end
  
  def create 
    @contact = Contact.find( params[:contact_id] )
    @report = @contact.build_report(report_params)
    if @report.save
      flash[:success] = "report Updated!"
      redirect_to contact_report_path( params[:contact_id] )
    else
      render action: :new
    end
  end
  
  def show
    # form where a Contact can fill out their own report.
    @contact = Contact.find( params[:contact_id] )
    @report = @contact.report
    @what = @contact.report.what
    @who = @contact.report.who
    @wiifm = @contact.report.wiifm
    @mobile = @contact.report.mobile
    @speed = @contact.report.speed
    @whattodo = @contact.report.whattodo
    
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "report",
        
         background:  true
        # Excluding ".pdf" extension.
      end
    end
  end
  
  def edit
    @contact = Contact.find( params[:contact_id] )
    @report = @contact.report
  end
  
  def update
    @contact = Contact.find( params[:contact_id] )
    @report = @contact.report
    if @report.update_attributes(report_params)
      flash[:success] = "report Updated!"
      redirect_to contact_report_path( params[:contact_id] )
    else
      render action: :edit
    end
  end

  def destroy
    @contact = Contact.find( params[:contact_id] )
    @report = @contact.report
    if @report.present?
      @report.destroy
      @contact.destroy
      redirect_to contacts_path
    else
      redirect_to contacts_path
    end
  end

  private
    def report_params
      params.require(:report).permit(:what, :who, :wiifm, :whattodo, :mobile, :speed)
    end
  
    #def only_current_Contact
      #@contact = Contact.find( params[:contact_id] )
      #redirect_to(root_url) unless @contact == current_Contact
    #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pdf_helper.rb
module PdfHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/contacts/_all.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2"> 
        <table class="table table-striped">
          <tr>
            <th>Name</th>
            <th>Email</th> 
            <th>URL</th>
          </tr>
          <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.name%></td>
            <td><%= contact.email %></td> 
            <td><%= contact.url %></td>
          </tr>
            <% end %>  
        </table>
    </div>        
</div>

app/views/contacts/_form.html.erb
  <%= form_for @contact,  html: { id: 'my_form1' } do |f| %>
  <div class="col-md-4 col-md-offset-4">
     
    <div class="form-group">
        <%= f.text_field :name, class: 'form-control transparent', placeholder: 'Name', required: true %>
      </div> 
      
      <div class="form-group">
        <%= f.email_field :email, class: 'form-control transparent', placeholder: 'Email', required: true %>
      </div> 
      
      <div class="form-group">
        <%= f.url_field :url, class: 'form-control transparent', placeholder: '(URL: http://mywebsite.com)', required: true %>
    </div>  
  
        <%= f.submit :'Analyze my website', class: "btn btn-success submission", required: true  %>
  </div>
  <% end %>
<script>
  $("#my_form1").validate();
</script>

app/views/contacts/_form2.html.erb
<%= form_for @contact, html: { id: 'my_form' } do |f| %>
  <div class="col-md-4 col-md-offset-4">
    
    <div class ="form-group">
      <p class="text-muted"></p>
      <div class="right-inner-addon ">
        <button style="display:none" class="success btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
        <button style="display:none" class="fail btn btn-warning"><span class="glyphicon glyphicon-flash"></span></button>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name', required: true %>
      </div>
    </div>
    
    <div class ="form-group">
      <p class="text-muted"></p>
      <div class="right-inner-addon ">
        <button style="display:none" class="success btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
        <button style="display:none" class="fail btn btn-warning"><span class="glyphicon glyphicon-flash"></span></button>
      <%= f.email_field :email, class: 'form-control', placeholder: 'Email', required: true %>
      </div>
    </div>

    <div class ="form-group">
      <p class="text-muted"></p>
      <div class="right-inner-addon ">
        <button style="display:none" class="success btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
        <button style="display:none" class="fail btn btn-warning"><span class="glyphicon glyphicon-flash"></span></button>
      <%= f.url_field :url, class: 'form-control', placeholder: 'http://yourwebsite.com', required: true %>
      </div>
    </div>

       
        <%= f.submit :'Analyze my website', class: "btn btn-lg submit"  %>
        <h6 class="text-center"><i class="fa fa-lock" aria-hidden="true"></i> We value your privacy and hate spammers. Unsubscribe anytime.</h6>  
  <% end %>
</div>

app/views/contacts/index.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class = "container">
    <ul class="nav navbar-nav navbar-right">
      <%= button_to "Sign Out", destroy_admin_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
    </ul>
  </di>
</nav>
<div class="row">
    <div class="col-md-8 col-md-offset-2"> 
    <h1 class="text-center bg-info" >Contacts and Reports</h1>
        <table class="table table-striped">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th> 
            <th>URL</th>
            <th>Generate</th>
            <th>View</th>
            <th>PDF</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.id %></td>
            <td><%= contact.name%></td>
            <td><%= contact.email %></td> 
            <td><%= contact.url %></td>
            <td><%= link_to 'Generate', new_contact_report_path(contact) %></td>
            <%if contact.report.present?%>
              <td><%= link_to 'View', contact_report_path(contact) %></td>
              <td><%= link_to 'Donwload PDF', contact_report_path(contact, format: :pdf) %></td>
              <td><%= link_to 'Edit',  edit_contact_report_path(contact) %></td>
              <td><%= link_to 'Delete',  contact_report_path(contact), method: :delete %></td>
            <%else%>
              <td>n/a</td>
              <td>n/a</td>
              <td>n/a</td>
            <%end%>
          </tr>
            <% end %>  
        </table>
    </div>        
</div>

app/views/contacts/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= @contact.url %></h1>
     <div class="well report-description report-block">
       <h3>Impression</h3>
       <%= @contact.report.impression %><br/>
     </div>
    <div class="well report-block contact-info">
      <h3>Mobile Friendly?</h3>
        <%= @contact.report.mobile %><br/>
      <h3>Speed</h3>  
        <%= @contact.report.speed %><br/>
    </div>  
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="navbar navbar-inverse ">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
     
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li ><%= link_to 'FAQ', faq_path %></li>
        </ul>
        
      </div><!-- /.navbar-collapse -->
          <p class="text-left">© <%= Time.current.year %> All Rights with Andrei Tobias </p>

    </div><!-- /.container-fluid -->
  </nav>
            

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Get more clients</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.min.js' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/additional-methods.min.js' %>
    

  </head>

  <body>
   
    <%= yield %>
    
  </body>
</html>

app/views/pages/_content.html.erb
<!--Header -->
<div class ="container-fluid content">      
  <div class="row bordered">
      <div class="col-12">
          <div class ="content-header">    
              <h3> Are you getting the most out of your website ? </h3>
              
              <h4>As a business owner, having a website in <%= Time.current.year %> is mandatory. But how well your website
              is treating its visitors is another story.<br><br> We strongly believe that every website should
              be a <b>marketing vehicle</b>. This means it should help you grow a relationship with your customers. Help you grow your business.<br><br>
              Three scientifically-backed key aspects could make or break your website. 
              <br><br>
              Is your website attracting customers or pusing them away? 

              </h4>
              <h3 class ="subtitle "> Here’s why you could be shooting your business<br> in the foot </h3>
          </div>   
      </div>    
  </div>
</div>


<!--Attention --> 
<div class ="container-fluid first bordered">  
  <div class="row">
      <div class = "col-md-6 icon">
        <div class="left">
          <%= image_tag('eye.png', class:'img-responsive') %>
        </div>
        <%= image_tag('2.jpg', class:'img-responsive show-me') %>
      </div> 
      <div class= "col-md-6 text">      
        <div class="container-fluid">
          
          <div class="animation-element slide-left testimonial">
            <div class="header">
              <div class="right">
                <h3> Your website might not be conveying the right thing straight away</h3>
                <br>
                <h4> What you communicate and how you do it in those first few secconds
            is vital to converting visitors into paying customers.<br> <br>
                Why? <br> <br> 
            The human attention span is around 7 seconds. Most of your website visitors are likely to leave your website in the first 7 seconds if you can’t pass this test.
               
                </h4>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<!--Mobile --> 
<div class ="container first bordered">      
  <div class="row">
       
    <div class="left">
        <%= image_tag('phone.png', class:'img-responsive') %>
      </div>
      
      <div class= "col-md-6 text">      
        <div class="container-fluid">
          <div class="animation-element slide-left testimonial">
            <div class="header">
              <div class="right">
                <h3>Your website might not be easy to read on mobile</h3>
                <br>
                <h4>If your website is not easy to read on mobile devices, as much as 59% of smartphone users will likely <i>never</i> return to your website.<br><br>
                By 2018 almost 80% of internet usage will be mobile. You could be missing out on thousands of potential clients. 

                <br><br>In this report you'll see if your website is mobile-friendly and what you can do about it if it's not. 
                </h4>
              </div>
            </div>
          </div>
      </div>
    </div>
    
    <div class = "col-md-6 icon">
      <%= image_tag('mobile.jpg', class:'img-responsive show-me') %>
    </div>
  </div>
</div>   
<!--Speed --> 
<div class ="container first bordered">      
  <div class="row">
      <div class = "col-md-6 icon ">
        <div class="left">
          <%= image_tag('watch.png', class:'img-responsive') %>
        </div>
          <%= image_tag('1.jpg', class:'img-responsive show-me') %>
      </div> 
      <div class= "col-md-6 text ">      
        <div class="container-fluid">
          
          <div class="animation-element slide-left testimonial ">
            <div class="header">
              <div class="right">
                <h3> Your website might not load fast enough </h3>
                <br>
                <h4>If your website takes longer than 3 secconds to load, <strong>almost half</strong> of your visitors will leave your 
                  page. No matter how great your product or service is. 

                  <br>
                </h4>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

<div class ="container first bordered">      
  <div class="row padd">
      <div class= "col-md-10 col-md-offset-1 ">      
        <div class="container-fluid">
          
          <div class="animation-element slide-left testimonial ">
            <h4>Enter your name, email and url and we will get back as soon as possible
              with <b>real, no tech-jargon tips </b> on how you can improve your website starting today.
              </h4>
          </div>
      </div>
    </div>
  </div>
</div>

<!--CTA 2 -->
<div class = "container">
  <div class="row">
    <div class ="col-md-6 col-md-offset-3">
      <div class="cta2">
        <btn class="btn btn-primary btn-lg submission2" data-toggle="modal" data-target="#myModal">ANALYZE MY WEBSITE</btn>
      </div>
    </div>
  </div>  
</div>




<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Free Website Checkup</h4>
      </div>
      <div class="modal-body">
        <%= render "contacts/form2"%>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>

  </div>
</div>

app/views/pages/_footer.html.erb
<footer class="footer">
  <nav class="navbar navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <p>© <%= Time.current.year %> All Rights with ATCmedia</p>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav nav-pills">
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</footer>


<!--

  <nav class="navbar navbar-inverse navbar-fixed-bottom">  <div class="container">
      <div class="col-md-6">
        <p>© <%= Time.current.year %> All Rights with ATCmedia</p>
      </div>
      <div class"collapse navbar-collapse">
      <div class="col-md-6">
        <ul class=" bottom_ul">
          <li><a href="#">atcmedia.com</a></li>
          <li><a href="#">About us</a></li>
          <li><a href="#">Blog</a></li>
          <li><a href="#">Faq's</a></li>
          <li><a href="#">Contact us</a></li>
          <li><a href="#">Site Map</a></li>
        </ul>
      </div>
      </div>
  </nav>

app/views/pages/_landing.html.erb
    <div class="container-fluid landing">
      <section id = "section02 " class ="demo">
  
            <div class ="jumbotron">
              
              <div class="col-md-8 col-md-offset-2">
                
                  <h3>Free Website Checkup</h3>     
                  <h1> Get More Customers <span class="phone">By Avoiding Critical Website Mistakes</span>  </h1> 
              </div>
              
              <div class="col-md-6 col-md-offset-3 subtitle"> 
              <h2 class ="screen">
              In this free <span class="italic">custom</span> report you will discover if your website is optimized to turn visitors into customers </h2>

              </div>
              
            </div>
            
            <div class="col-md-12">  
                  <%= render "contacts/form"%>
               
            <section id="section02" class="demo">
            	<a href="#section03"><span></span><p>More<p></a>
            </section>
            
         </div>    
          
    </section> 
</div>    
    

app/views/pages/_landing2.html.erb
<div class="container-fluid bg_image">
  <div class="row fill-viewport ">
   <div class="col-xs-12 col-sm-7 col-sm-offset-3 col-md-6 col-md-offset-6 col-lg-4 ">
    <div class="well margin">
      <div class ="form-group">
        <h4 class="text-muted text-center text-uppercase">Free Website Checkup</h4> 
        <h1 class="large text-center blue text-bold">Get More Customers By Avoiding Critical Website Mistakes </h1>
        
      <ul class="list">
        <h4>In this <u>free custom report </u> you'll leran: </h3>
        <br class ="hidden-xs">
        <h4><li class="item">If YOUR website is communicating the right thing in 7 seconds and what to do about it if it's not.
</li></h4>
        <br class ="hidden-xs">
        <h4><li class="item">How to avoid a simple 'rookie mistake' that could cost you more than half of potential customers. 
        </li></h4>
        <br class ="hidden-xs">
        <h4><li class="item">If YOUR website is fast enough and why this is critical. </li></h4>
      </ul> 
          <br class ="hidden-xs">
  </div>
  
<btn class="btn btn-lg submit" data-toggle="modal" data-target="#myModal">Yes, send me the free report!</btn>
<h6 class="text-center"><i class="fa fa-lock" aria-hidden="true"></i> We value your privacy and hate spammers. Unsubscribe anytime</h6>    
<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title align-center text-bold"> <b>Learn if you are getting the most out of your website. Get a free custom checkup in 24 hours.
        </b>
        </h4>
        
      </div>
      <div class="modal-body">
        <%= render "contacts/form2"%>
      </div>
      <div class="modal-footer">
          

      </div>
    </div>

  </div>
  
</div>
</div>  
  
 

app/views/pages/error.html.erb
<div class ="thankyou content container-fluid">
<div class="container"> 
  <div class="col-md-6 col-md-offset-3">
    <% flash.each do |key, value| %>
      <%= content_tag :div,value, class: "alert alert-#{key}" %>
    <%end%> 
  </div>
</div>
<div class="container-fluid">      
  <div class="row"> 
    <div class="col-md-4 col-md-offset-4">    
      <div class="notify error">
        <h1>Ooops!</h1>
          <div class="error-icon">
            <%= image_tag("close.png", size: "132x132")  %>
          </div>  
        <h4>Something went wrong and we didn't receive your message.</h4>  
        
        <h4>Make sure you entered a valid email address and websiite address ie. http://mywebsite.com</h4>
          <div class="container-fluid cta2">
            <div class ="row">
            <btn class="btn btn-primary btn-lg submission2" data-toggle="modal" data-target="#myModal">Try again</btn>
            <button type="button" class="btn btn-default btn-lg back"><%= link_to 'Go Back', root_path %></button>
            </div>
          </div>
       </div>
      </div> 
    </div>   
  </div>     
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Free Website Checkup</h4>
      </div>
      <div class="modal-body">
        <%= render "contacts/form2"%>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>

  </div>
</div>

app/views/pages/faq.html.erb
<div class ="faq container-fluid">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class ="text-center">Disclaimer and FAQ</h1>
      </div>  
    </div>
    <div class ="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well">
          <ol>
            <h3><li>What this report is:</li></h3>
            <p class="text-left text-muted">A simple yet comprehensive free review of your website, including techniques you can implement 
            right now to make sure you are not missing out on potential paying customers. </p>
            <h3><li>What this report is not:</li></h3>
              <ul class ="list-group">
                <li class="list-group-item text-muted">a review of your copywriting. We know our strenghts and copy is not one of them.  </li>
                <li class="list-group-item text-muted">a review of your product or service. Conversion (turning visitors into customers) can be influenced by a lot of factors – 
                including the product or service you are offering or if you are offering it to the right type of audience.</li>
                <li class="list-group-item text-muted">a gurantee that customers will come flying
                through your door once you implement what we suggest. Though they could be with some good marketing.</li>
              </ul>  
            <h3><li>How long does it take until I receive my report?</li></h3>
            <p class="text-left text-muted">Normally you should receive your report in 24 hours, however it may take up to 48 hours.</p>

            <h3><li>Any other questions? Drop us an <%= mail_to "me@domain.com", 'email!' %> </li></h3>
          </ol>
        </div> 
      </div>
    </div>  
 

</div>
<%= render "layouts/footer"%> 

app/views/pages/home.html.erb
<%= render "pages/landing"%>
      <!-- Content -->
<section id = "section03">
  <%= render "pages/content"%>
  
</section>
<%= render "layouts/footer"%>

app/views/pages/landing2.html.erb
<%= render "pages/landing2"%>

app/views/pages/thankyou.html.erb
<div class ="thankyou content container-fluid">
  <div class="container"> 
    <div class="col-md-6 col-md-offset-3">
      <% flash.each do |key, value| %>
        <%= content_tag :div,value, class: "alert alert-#{key}" %>
      <%end%> 
    </div>
  </div>
<div class="container-fluid">      
  <div class="row"> 
    <div class="col-md-4 col-md-offset-4">
      <div class="notify check ">
        <h1>Thank you!</h1>
          <div class="check-icon">
            
            <%= image_tag("check.png", size: "132x132")  %>
            
            
          </div>  
        <h4>We received your message.</h4>  
        
        <h4>Keep an eye on your inbox. We'll visit your website, rate it and get back to you with valuable insights within the next
        24 hours! </h4>
        
        <button type="button" class="btn btn-primary btn-lg back2"><%= link_to 'Go Back', root_path %></button>
       </div>
    </div>   
  </div>

</div>  
</div>

app/views/reports/_fast.html.erb
<h3 class="bordered"><%= image_tag("star.png", size: "64x64")%> &nbsp; Congratulations your website is <i>uber</i> fast! </h3>
             
  <p> Having a fast website is key to getting and keeping cusotmers interested in what you have to say. 
  Most probably your customers never complained that your website is slow. 
  </p>
  
<h3 class="bordered"><%= image_tag("chat.png", size: "64x64")%> &nbsp; Ok, so what should I do now?</h3>
      <p>Whatever you're doing keep up the good work! Your website is fast and you should be proud. 
      Even though your website loads very fast, you should periodically check its loading time. A few good
      resources <%=link_to 'GTmetrix', 'https://gtmetrix.com/'%> and <%=link_to 'Pingdom', 'https://tools.pingdom.com/'%>.
      </p>  

app/views/reports/_friendly.html.erb
<h3 class="bordered"><%= image_tag("trophy.png", size: "64x64")%> &nbsp; Congratulations your website is mobile-friendly </h3>
             
  <p>Having a mobile-friendly website is especially key to getting new customers interested in what you have to say. 
  Most probably your visitors never complained that your website is not visible on mobile or left your page because of this. </p>
  
<h3 class="bordered"><%= image_tag("chat.png", size: "64x64")%> &nbsp; Ok, so what should I do?</h3>
    <p>Keep up the good work! Your website is visible on smaller screens!</p>  

app/views/reports/new.html.erb
<h5><%= @contact.url %></h5>